### PR TITLE
imagecodecs 2024.9.22

### PR DESCRIPTION
**Pull request by skupr-anaconda**
**Destination channel:** main

### Links

- [PKG-6186](https://anaconda.atlassian.net/browse/PKG-6186) 
- [Upstream repository](https://github.com/cgohlke/imagecodecs/tree/v2024.9.22)
- Changelog:https://github.com/cgohlke/imagecodecs/blob/v2024.9.22/CHANGES.rst
- Requirements:
  - https://github.com/cgohlke/imagecodecs/tree/v2024.9.22?tab=readme-ov-file#requirements
  - https://github.com/cgohlke/imagecodecs/blob/v2024.9.22/pyproject.toml
  - https://github.com/cgohlke/imagecodecs/blob/v2024.9.22/setup.py

### Explanation of changes:

- Remove obsolete or duplicated patches
- Refresh [0003-jpeg8_use_shared_libjpeg.patch](https://github.com/AnacondaRecipes/imagecodecs-feedstock/pull/17/files#diff-22696b27533f24df4997b2bddad7f3ea785f7c42ea1c481980ddb9b4f417e51b)
- Set `openjpeg=2.3` on Windows because our `cbc.yaml` pins to **2.3**, see https://github.com/AnacondaRecipes/aggregate/blob/master/conda_build_config.yaml#L191 
- Add missing `#!/bin/bash` to `build.sh`
- Create a new [fix-customize-build.patch](https://github.com/AnacondaRecipes/imagecodecs-feedstock/pull/17/files#diff-367f47403fba9dfc88bd3d69f6c482af2280fa13bf8f09d952ac0968e713e044) to fix all dependency issues
- Reset the build number to `0`
- Skip `py<39`
- Enable support for **py313** by adding `ANACONDA_ROCKET_ENABLE_PY313 : yes` to `abs.yaml`
- Use **numpy 2** in `host`
- Add `zlib-ng 2.0` to `host` because we have this package on defaults for all platforms
- Update pinnings for: `lcms2 2.16`, `libaec 1`, `libtiff 4.5.1`, `lerc 4,` `libdeflate 1.22`, `libavif 1.1.1` (see the build order below)
- Remove a runtime pinning for `libdeflate`
- Use a plain `numpy` in `run`
- Skip some tests, mainly because of upstream issues or incompatibilities on requested platforms, etc. FYI, `conda-forge` doesn't run the test suite by default, they only check available _codecs_, see https://github.com/conda-forge/imagecodecs-feedstock/blob/main/recipe/meta.yaml#L64-L83

### Notes:

- Related updates and rebuilds (aka the `imagecodecs` build order):
  - libavif 1.1.1 https://github.com/AnacondaRecipes/libavif-feedstock/pull/2
  - libaec 1.1.3 https://github.com/AnacondaRecipes/libaec-feedstock/pull/3
  - lcms2 2.16: with libtiff 4.5.1 https://github.com/AnacondaRecipes/lcms2-feedstock/pull/1
    - poppler 24.09.0: rebuild with libtiff 4.5.1 and licms2 2.16 https://github.com/AnacondaRecipes/poppler-feedstock/pull/18
  - lerc 4.0.4 https://github.com/AnacondaRecipes/lerc-feedstock/pull/3
  - libdeflate 1.22 https://github.com/AnacondaRecipes/libdeflate-feedstock/pull/6
    - librsvg 2.56.3: rebuild with libdeflate 1.22 https://github.com/AnacondaRecipes/librsvg-feedstock/pull/9
    - pysam 0.22.1: build with libdeflate 1.22 https://github.com/AnacondaRecipes/pysam-feedstock/pull/2 :snowflake:
    - libtiff 4.5.1: rebuild with lerc 4 and libdeflate 1.22 https://github.com/AnacondaRecipes/libtiff-feedstock/pull/20
      - libgdal/gdal 3.6.2: rebuild with libtiff 4.5.1, lerc 4 and libdeflate 1.22 https://github.com/AnacondaRecipes/gdal-feedstock/pull/29
      - pillow 11.0.0: rebuild with lcms2 2.16 and libtiff 4.5.1 https://github.com/AnacondaRecipes/pillow-feedstock/pull/26

[PKG-6186]: https://anaconda.atlassian.net/browse/PKG-6186?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by skupr-anaconda** [comment]
An error:
`imagecodecs/_aec.c:20724:40: error: use of undeclared identifier 'AEC_VERSION_MAJOR'`

We need to update `libaec` to **1.1.3** because `imagecodecs >=24.1.1` requires `libaec 1.1`,  see https://github.com/cgohlke/imagecodecs/blob/v2024.9.22/CHANGES.rst#revisions

**Comment by skupr-anaconda** [comment]
An error:
`imagecodecs/_avif.c:23082:30: error: 'avifEncoder' has no member named 'quality'`
We have to update `libavif` to `>=1.0.0`, see https://github.com/AOMediaCodec/libavif/blob/main/CHANGELOG.md#100---2023-08-24

**Comment by skupr-anaconda** [comment]
An error:
```
  [1/1] Cythonizing imagecodecs/_jpeg8.pyx
  building 'imagecodecs._jpeg8' extension

  /croot/imagecodecs_1733313422964/_build_env/bin/x86_64-conda-linux-gnu-cc -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -Wall -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /croot/imagecodecs_1733313422964/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/include -I/croot/imagecodecs_1733313422964/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/include -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /croot/imagecodecs_1733313422964/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/include -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /croot/imagecodecs_1733313422964/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/include -fdebug-prefix-map=/croot/imagecodecs_1733313422964/work=/usr/local/src/conda/imagecodecs-2024.9.22 -fdebug-prefix-map=/croot/imagecodecs_1733313422964/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place=/usr/local/src/conda-prefix -I/croot/imagecodecs_1733313422964/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/include/openjpeg-2.3 -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /croot/imagecodecs_1733313422964/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/include -fPIC -DNPY_NO_DEPRECATED_API=NPY_1_20_API_VERSION -Iimagecodecs -I/croot/imagecodecs_1733313422964/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/include/python3.9 -I/croot/imagecodecs_1733313422964/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/python3.9/site-packages/numpy/_core/include -c imagecodecs/_jpeg8.c -o build/temp.linux-x86_64-cpython-39/imagecodecs/_jpeg8.o

  imagecodecs/_jpeg8.c: In function '__pyx_pf_11imagecodecs_6_jpeg8_jpeg8_version':

  imagecodecs/_jpeg8.c:20696:36: error: 'LIBJPEG_TURBO_VERSION_NUMBER' undeclared (first use in this function)

  20696 |   __pyx_t_1 = __Pyx_PyInt_From_int(LIBJPEG_TURBO_VERSION_NUMBER); if (unlikely(!__pyx_t_1)) __PYX_ERR(0, 84, __pyx_L1_error)
```

It seems we should replace `jpeg` with `libjpeg-turbo` as conda-forge did, see https://github.com/conda-forge/imagecodecs-feedstock/commit/f6350f89d215833dcb78b8d45f0e18955042b615

**Comment by skupr-anaconda** [comment]
Hm... we can't use `libjpeg-turbo` if other packages were built with `jpeg`:

```
    The following packages are incompatible
    ├─ libjpeg-turbo 3.*  is installable and it requires
15:16:00
    │  └─ jpeg <0.0.0a , which can be installed;
    └─ libwebp 1.3.2.*  is not installable because it requires
       └─ jpeg >=9e,<10a , which conflicts with any installable versions previously reported.
```

**Comment by skupr-anaconda** [comment]
The tests failed on `linux-64`:
```
E   imagecodecs._deflate.DeflateError: libdeflate_zlib_compress returned unknown error '0'

imagecodecs/_deflate.pyx:155: DeflateError
```

**Comment by skupr-anaconda** [comment]
Also `test_cms_identity_transforms` fails:
```
E           AssertionError:
E           Not equal to tolerance rtol=1e-07, atol=0.001
```

**Comment by skupr-anaconda** [comment]
An error on `s390x`:
```
conda_build.exceptions.OverLinkingError: overlinking check failed

    ["  ERROR (imagecodecs,lib/python3.10/site-packages/imagecodecs/_lerc.cpython-310-s390x-linux-gnu.so): .. but ['defaults/linux-s390x::lerc==3.0=hd8db5ea_0'] not in reqs/run, (i.e. it is overlinking) (likely) or a missing dependency (less likely)"]
```

**Comment by skupr-anaconda** [comment]
> A new error:
> 
> ```
>   [1/1] Cythonizing imagecodecs/_jpegxr.pyx
>   building 'imagecodecs._jpegxr' extension
> 
>   x86_64-apple-darwin13.4.0-clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -isystem /var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_d2r_mtf5ti/croot/imagecodecs_1733325082406/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/include -arch x86_64 -I/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_d2r_mtf5ti/croot/imagecodecs_1733325082406/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/include -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -isystem /var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_d2r_mtf5ti/croot/imagecodecs_1733325082406/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/include -arch x86_64 -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -isystem /var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_d2r_mtf5ti/croot/imagecodecs_1733325082406/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/include -fdebug-prefix-map=/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_d2r_mtf5ti/croot/imagecodecs_1733325082406/work=/usr/local/src/conda/imagecodecs-2024.9.22 -fdebug-prefix-map=/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_d2r_mtf5ti/croot/imagecodecs_1733325082406/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl=/usr/local/src/conda-prefix -I/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_d2r_mtf5ti/croot/imagecodecs_1733325082406/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/include/openjpeg-2.3 -D_FORTIFY_SOURCE=2 -isystem /var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_d2r_mtf5ti/croot/imagecodecs_1733325082406/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/include -mmacosx-version-min=10.15 -DNPY_NO_DEPRECATED_API=NPY_1_20_API_VERSION -D__ANSI__=1 -Iimagecodecs -I/usr/include/jxrlib -I/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_d2r_mtf5ti/croot/imagecodecs_1733325082406/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/include/python3.9 -I/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_d2r_mtf5ti/croot/imagecodecs_1733325082406/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib/python3.9/site-packages/numpy/_core/include -c imagecodecs/_jpegxr.c -o build/temp.macosx-10.15-x86_64-cpython-39/imagecodecs/_jpegxr.o
> 
>   imagecodecs/_jpegxr.c:1269:10: fatal error: 'windowsmediaphoto.h' file not found
> 
>   #include "windowsmediaphoto.h"
> ```
> 
> see also [cgohlke/imagecodecs#5 (comment)](https://github.com/cgohlke/imagecodecs/issues/5#issuecomment-750891554)
> 
> We must patch the upstream `setup.py` to set the `include` folder properly.

TODO: The same patch for `win-64` too

**Comment by skupr-anaconda** [comment]
An error on linux-64. Tests failed:
`Fatal Python error: Segmentation fault`

**Comment by skupr-anaconda** [comment]
Finally, all platforms succeeded.

File: recipe/0003-jpeg8_use_shared_libjpeg.patch [hunk 1]
```diff
@@ -1,12 +1,13 @@
 diff --git a/setup.py b/setup.py
+index a7568a1..5e00997 100644
 --- a/setup.py
 +++ b/setup.py
-@@ -145,7 +145,7 @@ EXTENSIONS = {
-         libraries=['openjp2', 'lcms2'],
+@@ -180,7 +180,7 @@ EXTENSIONS = {
      ),
      'jpeg8': ext(
+         sources=['imagecodecs/_jpeg8_legacy.pyx'],
```
Comment (danpetry) [inline recipe/0003-jpeg8_use_shared_libjpeg.patch:8]: I'm not sure this patch is needed any more, see [here](https://github.com/AnacondaRecipes/jpeg-feedstock/pull/6) and [here](https://github.com/AnacondaRecipes/jpeg-feedstock/pull/7)

File: recipe/meta.yaml [hunk 2]
```diff
@@ -55,29 +56,53 @@ requirements:
...
+    - libavif 1.1.1
 
   run:
-    - libdeflate >=1.17,<1.18.0a0
+    - libdeflate
     - python
     # Work around missing `run_exports` in defaults package
     - "{{ pin_compatible('brotli', max_pin='x.x') }}"
-    - {{ pin_compatible('numpy') }}
+    - numpy
```
Comment (danpetry) [inline recipe/meta.yaml:81]: numpy still needs to be above 1.2something and less than 3 I think, although in practice not pinning shouldn't matter too much. The upper bound might be helpful for when we update numpy to v3 (hopefully not soon)

File: recipe/meta.yaml [hunk 3]
```diff
@@ -91,24 +116,9 @@ test:
...
-    - pytest -vv test_imagecodecs.py -k "not (test_jpeg_rgb_mode or test_jpeg2k_numthreads or test_image_roundtrips[jpeg2k-uint16-rgb-out-bytearray-None)"  # [linux and not s390x]
-    - pytest -vv test_imagecodecs.py -k "not (test_jpeg2k_numthreads or test_packints_decode or test_floatpred or test_float24 or test_jpegsof3 or test_image_roundtrip or test_spng_encode or test_ljpeg or test_jpeg_rgb_mode or test_cms_format)"  # [s390x]
-
-    - pytest -vv test_imagecodecs.py -k "not (test_cms_profile or test_jpeg_rgb_mode)"  # [win]
-
-    # CAPTURING FAILING S390x tests to be reviewed later (These tests are failing most likely from an upstream Endianess issue)
-    # These may be fixed with future versions but needs to be checked.
-    # - pytest -vv test_imagecodecs.py -k "test_jpeg2k_numthreads and test_packints_decode and test_floatpred and test_float24 and test_jpegsof3 and test_image_roundtrips and test_spng_encode and test_ljpeg and test_jpeg_rgb_mode and test_cms_format" || true  # [s390x]
+    - pytest -vv test_imagecodecs.py -k "not ({{ tests_to_skip }})"
```
Comment (danpetry) [inline recipe/meta.yaml:121]: do you want to include the expected_codecs test from conda-forge? It could be a way to clearly document what's supported. maybe at the top of the feedstock.

File: recipe/meta.yaml [hunk 4]
```diff
@@ -40,9 +39,11 @@ requirements:
...
-    - numpy {{ numpy }}
-    - cython 0.29
+    - numpy 2.0 # [py<313]
+    - numpy 2.1 # [py==313]
+    - cython >=3.0.11
     - zlib {{ zlib }}
+    - zlib-ng 2.0
     - bzip2 {{ bzip2 }}
     - xz {{ xz }}
     - zstd 1.5.5
```
Comment (danpetry) [inline recipe/meta.yaml:49]:
```suggestion
    - zstd 1.5.6
```
https://github.com/cgohlke/imagecodecs/tree/v2024.9.22?tab=readme-ov-file#requirements

File: recipe/meta.yaml [hunk 5]
```diff
@@ -55,29 +56,53 @@ requirements:
...
     - openjpeg {{ openjpeg }}
     - blosc 1.21.3
-    - lcms2 2.12
-    - libaec 1.0.4
+    - lcms2 2.16
+    - libaec 1
     - brotli 1.0.9
     - libzopfli 1.0.3
     - charls 2.2.0            # [not s390x]
     - snappy 1.1.9
```
Comment (danpetry) [inline recipe/meta.yaml:64]:
```suggestion
    - snappy 1.2.1
```
https://github.com/cgohlke/imagecodecs/tree/v2024.9.22?tab=readme-ov-file#requirements

File: recipe/meta.yaml (hunk 4 above)
Comment (danpetry) [reply recipe/meta.yaml:49]: or maybe pin to cbc.yaml if that will work

**Review by danpetry — COMMENTED** [review]
Review of recipe and dependencies etc. Still need to review the codecs that are included.
As a general point, where there were conflicts between [imagecodecs' stated requirements](https://github.com/cgohlke/imagecodecs/tree/v2024.9.22?tab=readme-ov-file#requirements) and our cbc.yaml (eg. zstd), is it worth trying to align with cbc.yaml instead? The requirements there say "other versions may work".

File: recipe/meta.yaml (hunk 2 above)
Comment (skupr-anaconda) [reply recipe/meta.yaml:81]: It's not clear what the lower bound of numpy is. They only dropped support for `Python 3.8` and `numpy < 1.21` (NEP29) in **v2023.7.4**. I'll set it in the recipe as `numpy >=1.21,<3`

File: recipe/meta.yaml (hunk 3 above)
Comment (skupr-anaconda) [reply recipe/meta.yaml:121]: Yes, thanks for reminding me.

File: recipe/meta.yaml (hunk 5 above)
Comment (skupr-anaconda) [reply recipe/meta.yaml]: Done

File: recipe/meta.yaml (hunk 4 above)
Comment (skupr-anaconda) [reply recipe/meta.yaml]: I'll try with `zstd {{ zstd }}`

File: recipe/0003-jpeg8_use_shared_libjpeg.patch (hunk 1 above)
Comment (skupr-anaconda) [reply recipe/0003-jpeg8_use_shared_libjpeg.patch:8]: I removed this patch. Thanks!

File: recipe/meta.yaml (hunk 3 above)
Comment (skupr-anaconda) [reply recipe/meta.yaml:123]: I've checked that there are ~200 codecs at all, see https://github.com/cgohlke/imagecodecs/blob/v2024.9.22/tests/test_imagecodecs.py. If the codec is missing, then the corresponding test is skipped. I'll look at the logs and see which codecs are skipped

**Review by JamesRobertsonGames — APPROVED** [review]
Happy with this from the looks of it, Everything has been tested in detail and comments seem to be addressed.

File: recipe/fix-customize-build.patch [hunk 6]
```diff
@@ -0,0 +1,74 @@
...
+     del EXTENSIONS['lzham']
+@@ -527,9 +528,9 @@ def customize_build_condaforge(EXTENSIONS, OPTIONS):
+     del EXTENSIONS['sperr']
+     del EXTENSIONS['sz3']
+     del EXTENSIONS['ultrahdr']
+-    del EXTENSIONS['zlibng']
++    del EXTENSIONS['blosc2']  # c-blosc2 library not commonly available
+ 
+-    EXTENSIONS['jpeg8']['sources'] = []  # use libjpeg-turbo 3
++    #EXTENSIONS['jpeg8']['sources'] = []  # use libjpeg-turbo 3
```
Comment (Cansisti) [inline recipe/fix-customize-build.patch:38]: Nitpick - might be beneficial to leave a comment here why this is commented out.

**Review by Cansisti — APPROVED** [review]

File: recipe/fix-customize-build.patch (hunk 6 above)
Comment (skupr-anaconda) [reply recipe/fix-customize-build.patch:38]: I left a comment in `meta.yaml` about all the fixes that the patch is doing
